name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust if needed
          cache: 'npm'       # Or 'yarn' if you use yarn

      - name: Install dependencies
        run: npm install --legacy-peer-deps # Or 'yarn install'
        working-directory: ./port # Correct placement for this step

      - name: Build Next.js app
        run: npm run build # Or 'yarn build'
        working-directory: ./port # Correct placement for this step

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './port/out' # IMPORTANT: This path is correct for the 'out' folder inside 'port'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4